pipeline {
    agent any

    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
        IMAGE_NAME = "saikiranmara/cicd-e2e"
        REPO_URL = "https://github.com/saikiran146/Jenkins.git"
        REPO_SUBDIR = "python-jenkins-argocd-k8s"
    }

    stages {

        stage('Checkout repo') {
            steps {
                dir('repo') {
                    git url: "${REPO_URL}", branch: 'main'
                }
            }
        }

        stage('Build Docker') {
            steps {
                dir("repo/${REPO_SUBDIR}") {
                    sh '''
                    echo "Building docker image..."
                    docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
                    '''
                }
            }
        }

        stage('Docker Login & Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-hub',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    docker push ${IMAGE_NAME}:${IMAGE_TAG}
                    '''
                }
            }
        }

        stage('Update K8s Manifest') {
            steps {
                dir("repo/${REPO_SUBDIR}") {
                    sh '''
                    echo "Checking YAML files..."
                    ls deploy/*.yaml || true

                    if [ -f deploy/deploy.yaml ]; then
                      sed -i "s|image:.*|image: ${IMAGE_NAME}:${IMAGE_TAG}|g" deploy/deploy.yaml
                      echo "Updated deploy.yaml:"
                      cat deploy/deploy.yaml
                    else
                      echo "deploy.yaml not found"
                    fi
                    '''
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline finished"
            sh 'docker logout || true'
        }
    }
}
